# Omakase Ruby styling for Rails
plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot
  - rubocop-obsession
  - rubocop-thread_safety

inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Include:
    - "**/*"
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - head
    - raise
    - render
  Exclude:
    - 'db/migrate/*'
    - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent